# Generated by Django 5.0.3 on 2024-05-21 08:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stream", "0002_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
